### PR TITLE
Make `exports: :all` also export subdomains

### LINKED ISSUE #59: Subdomains unexpected boundary violation
👋 Howdy. I'm experiencing an issue with subdomains.

Below is a contrived example - I am actually having this issue in a larger codebase and wanted to reproduce it on a smaller scale.

If I have these boundaries:

* `Blah` (deps: [], exports: :all)
  * `Blah.Context` (deps: [], exports: :all)
* `BlahWeb` (deps: [Blah], exports: :all)

Then I have a file `Blah.Context.Subcontext.Module` with a `call/0` 

Compiling gives a forbidden reference error. This is unexpected to me, since `Blah` exports `:all` and `Blah.Context` exports all.

**What I've tried**
* ❌ Using `exports: [{Subcontext, []}]` syntax does not help.
* ✅ If I specify in `Blah.Context` the exact modules to export (`exports: [Subcontext.Module]`), the violation disappears.
* ❌ Adding a boundary on `Blah.Context.Subcontext` and exporting all does not help.
  * ❌ If I export `Module` in `Subcontext`, the violation is still present which surprises me since exporting `Subcontext.Module` from `Context` _did_ work.

I've demonstrated this in [this repo](https://github.com/aspett/boundary-issue-example) where if you compile on `main`, you'll see the violation.

```
warning: forbidden reference to Blah.Context.Subcontext.Module
  (references from BlahWeb to Blah.Context are not allowed)
  lib/blah_web/controllers/page_html/home.html.heex:1
```

Any thoughts / help would be greatly appreciated 🙏. I'm not sure if I've just missed how this case should be idiomatically handled, or if this is a bug, or not a feature at all.

Thank you

### PR DESCRIPTION
**Pull request by Nezteb**
Should resolve #59, though there might be cases I've missed.

### CODE REVIEW

**Comment by Nezteb** [comment]
I'm missing something, because two tests now fail:
```
  1) test mass-export of a sub-boundary (Mix.Tasks.Compile.BoundaryTest)
     test/mix/tasks/compile/boundary_test.exs:847
     match (=) failed
     code:  assert [warning] = warnings
     left:  [warning]
     right: []
     stacktrace:
       test/mix/tasks/compile/boundary_test.exs:872: (test)

  2) test non-exported module of a sub-boundary isn't included in a mass export list of the parent boundary (Mix.Tasks.Compile.BoundaryTest)
     test/mix/tasks/compile/boundary_test.exs:899
     match (=) failed
     code:  assert [warning] = warnings
     left:  [warning]
     right: []
     stacktrace:
       test/mix/tasks/compile/boundary_test.exs:919: (test)
```

So I will work on fixing those!

File: lib/boundary/checker.ex [hunk 1]
```diff
@@ -127,8 +127,15 @@ defmodule Boundary.Checker do
...
         |> Enum.find(&(Enum.at(&1.ancestors, 0) == boundary.name))
         |> case do
-          nil -> false
-          child_subboundary -> export in [child_subboundary.name | child_subboundary.exports]
+          nil ->
+            false
+
+          # If the export's `owner_boundary` exports all modules, include sub-modules
+          %{exports: [{export_module, []}]} ->
+            String.starts_with?(to_string(export), to_string(export_module))
```
Comment (sasa1977) [inline lib/boundary/checker.ex:135]: From what I understand, this will also export private sub-boundary modules. I find this a bit weird, because we can end up with a scenario that some modules are private to other modules in the common parent boundary, but they can be used by the modules outside of that parent boundary. 

So I think we should only include public sub-boundary modules, as mentioned in the [last comment in #59](https://github.com/sasa1977/boundary/issues/59#issuecomment-2374906436).

Bubbling up should also work, for example:

- if `Foo.Bar.Baz` is a sub-sub-boundary
- and `Foo.Bar` exports `Foo.Bar.Baz`
- then exporting all from `Foo` should also include exports from `Foo.Bar.Baz`

File: test/mix/tasks/compile/boundary_test.exs [hunk 2]
```diff
@@ -1147,13 +1147,27 @@ defmodule Mix.Tasks.Compile.BoundaryTest do
...
+  module_test "exporting all modules and sub-modules",
               """
               defmodule #{module1} do
                 use Boundary, exports: :all
 
                 defmodule Schemas.Foo do def fun(), do: :ok end
                 defmodule Schemas.Bar do def fun(), do: :ok end
+
+                defmodule SubModule do
+                  use Boundary, exports: :all
```
Comment (sasa1977) [inline test/mix/tasks/compile/boundary_test.exs:1159]: Instead of this I propose `exports: [Module]`, and then we can check that `Module.Another` (perhaps renamed to `Module.Private`) is not exported. We also need to expand this test to check if bubbling-up works as expected. This can all be done within the same test.

File: test/mix/tasks/compile/boundary_test.exs [hunk 3]
```diff
@@ -1147,13 +1147,27 @@ defmodule Mix.Tasks.Compile.BoundaryTest do
   module1 = unique_module_name()
   module2 = unique_module_name()
 
-  module_test "exporting all modules",
+  module_test "exporting all modules and sub-modules",
```
Comment (sasa1977) [inline test/mix/tasks/compile/boundary_test.exs:1150]:
```suggestion
  module_test "exporting all modules and exports of all nested boundaries",
```

File: test/mix/tasks/compile/boundary_test.exs (hunk 2 above)
Comment (Nezteb) [reply test/mix/tasks/compile/boundary_test.exs]: Updated the test to use `exports: [Module]`!

File: test/mix/tasks/compile/boundary_test.exs (hunk 3 above)
Comment (Nezteb) [reply test/mix/tasks/compile/boundary_test.exs]: Updated!

File: lib/boundary/checker.ex (hunk 1 above)
Comment (Nezteb) [reply lib/boundary/checker.ex:135]: Even with the updated `exports: [Module]` test, this logic still seems to work, I think because this function is only looking at the current export and its immediate parent boundary?

I tried writing a few different tests to see if they'd fail but couldn't find any issues with the exported vs private sub-boundaries.

**Comment by sasa1977** [comment]
I did some local experiments, and this is still not working properly with respect to sub-sub-boundaries. But it doesn't seem to be the problem of this PR, because I'm able to reproduce the issue on the master too. So I'll just merge this, and then try to resolve it separately. Thanks for the contribution!
